[unstable]
build-std = ["core", "std", "alloc", "proc_macro", "panic_abort"]
trim-paths = true

[target.x86_64-apple-darwin]
linker = "clang"
rustflags = ["-C", "target-cpu=x86-64-v2"]

[target.aarch64-apple-darwin]
linker = "clang"
rustflags = ["-C", "target-cpu=apple-m1"]
